
//Variables ("now in getFormData()");
const S = document.getElementById("stockprice").value.trim();
const SP = document.getElementById("strikeprice").value.trim();

const B = document.getElementById("expirationdate").value.trim();
const V = document.getElementById("vix").value.trim();
const RF = document.getElementById("RFR").value.trim();
//("clickme");

function submission() {
    alert("Hi there!");

   
};